/**
 * SevaSetu AI — Reports Page
 * Author: Rahul Jha | Made in India 🇮🇳
 */
import { useState } from "react";
import { reportAPI } from "../services/api";
import { useToast } from "../components/MainLayout";

const CHECKLISTS = [
  { key:"voter_id_new",        label:"Voter ID Registration",  icon:"🗳️" },
  { key:"voter_id_correction", label:"Voter ID Correction",    icon:"✏️" },
  { key:"pan_card",            label:"PAN Card Application",   icon:"💳" },
  { key:"passport",            label:"Passport Application",   icon:"📘" },
  { key:"income_certificate",  label:"Income Certificate",     icon:"📋" },
  { key:"birth_certificate",   label:"Birth Certificate",      icon:"📜" },
];

export default function ReportsPage() {
  const showToast = useToast();
  const [loading, setLoading] = useState({});

  const download = async (type, id) => {
    setLoading(l => ({ ...l, [type]: true }));
    try {
      if (type === "history") await reportAPI.downloadHistoryPDF();
      else if (type.startsWith("checklist_")) await reportAPI.downloadChecklistPDF(type.replace("checklist_", ""));
      showToast?.("PDF downloaded successfully!", "success");
    } catch { showToast?.("Download failed. Please try again.", "error"); }
    finally { setLoading(l => ({ ...l, [type]: false })); }
  };

  return (
    <div style={{ padding:20, height:"100%", overflowY:"auto", maxWidth:800, margin:"0 auto" }}>
      <h1 style={{ color:"var(--text)", marginBottom:4 }}>📊 PDF Reports</h1>
      <p className="text-muted" style={{ marginBottom:24 }}>Download professional PDF reports generated by SevaSetu AI</p>

      <div style={{ background:"var(--surface)", border:"1px solid var(--border)", borderRadius:"var(--radius-lg)", padding:20, marginBottom:16 }}>
        <h3 style={{ color:"var(--text)", marginBottom:14 }}>📝 Query History</h3>
        <p className="text-muted" style={{ marginBottom:12 }}>Export your last 20 AI interactions as a formatted PDF report.</p>
        <button className="btn btn-primary" onClick={() => download("history")} disabled={loading.history}>
          {loading.history ? <><div className="spinner sm"/>Generating...</> : "📥 Download History PDF"}
        </button>
      </div>

      <div style={{ background:"var(--surface)", border:"1px solid var(--border)", borderRadius:"var(--radius-lg)", padding:20 }}>
        <h3 style={{ color:"var(--text)", marginBottom:14 }}>📋 Document Checklists</h3>
        <p className="text-muted" style={{ marginBottom:14 }}>Download printable document checklists for government services.</p>
        <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))", gap:10 }}>
          {CHECKLISTS.map(({ key, label, icon }) => (
            <div key={key} style={{ background:"var(--surface-2)", border:"1px solid var(--border)", borderRadius:"var(--radius-md)", padding:14, display:"flex", alignItems:"center", justifyContent:"space-between", gap:10 }}>
              <span style={{ fontSize:"0.875rem", color:"var(--text)" }}>{icon} {label}</span>
              <button className="btn btn-secondary btn-sm" onClick={() => download(`checklist_${key}`)} disabled={loading[`checklist_${key}`]}>
                {loading[`checklist_${key}`] ? "..." : "📥"}
              </button>
            </div>
          ))}
        </div>
      </div>

      <div style={{ marginTop:16, background:"var(--accent-muted)", border:"1px solid var(--accent)", borderRadius:"var(--radius-md)", padding:"12px 16px", fontSize:"0.85rem", color:"var(--text-2)" }}>
        ℹ️ PDFs are generated server-side using ReportLab and include SevaSetu AI branding, India tricolor theme, official disclaimers, and source citations. <strong style={{color:"var(--text)"}}>Developed by Rahul Jha | Made in India 🇮🇳</strong>
      </div>
    </div>
  );
}
