"""
SevaSetu AI — PDF Report Generation Service
Author: Rahul Jha | Made in India 🇮🇳

Generates professional PDF reports for:
- Individual query answers (service guidance PDFs)
- Document checklists
- Scheme eligibility summaries
- User query history exports
"""

from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime, timezone
import io
import logging

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from app.core.database import get_db
from app.core.auth import get_current_active_user
from app.models.user import User, QueryHistory

logger = logging.getLogger(__name__)
router = APIRouter()


# ── COLOUR PALETTE (India Tricolor inspired) ──────────────────────────────────

SAFFRON   = colors.HexColor("#FF6B00")
GREEN_IN  = colors.HexColor("#138808")
NAVY      = colors.HexColor("#003580")
GOLD      = colors.HexColor("#FFD700")
LIGHT_BG  = colors.HexColor("#FFF8F0")
DARK_TEXT = colors.HexColor("#1a1a2e")
GREY_TEXT = colors.HexColor("#6b7280")
WHITE     = colors.white
BLACK     = colors.black


def _build_styles():
    """Build custom ReportLab paragraph styles."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title", parent=base["Title"],
            fontSize=22, textColor=SAFFRON,
            fontName="Helvetica-Bold",
            alignment=TA_CENTER, spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle", parent=base["Normal"],
            fontSize=11, textColor=GREY_TEXT,
            alignment=TA_CENTER, spaceAfter=16,
        ),
        "heading": ParagraphStyle(
            "Heading", parent=base["Heading2"],
            fontSize=13, textColor=NAVY,
            fontName="Helvetica-Bold",
            spaceBefore=12, spaceAfter=4,
            borderPad=4,
        ),
        "body": ParagraphStyle(
            "Body", parent=base["Normal"],
            fontSize=10, textColor=DARK_TEXT,
            leading=16, spaceAfter=6,
        ),
        "small": ParagraphStyle(
            "Small", parent=base["Normal"],
            fontSize=8, textColor=GREY_TEXT,
            leading=12,
        ),
        "footer": ParagraphStyle(
            "Footer", parent=base["Normal"],
            fontSize=8, textColor=GREY_TEXT,
            alignment=TA_CENTER,
        ),
        "badge": ParagraphStyle(
            "Badge", parent=base["Normal"],
            fontSize=9, textColor=WHITE,
            fontName="Helvetica-Bold",
            alignment=TA_CENTER,
        ),
    }


def _build_header(styles: dict, title: str, subtitle: str, user_name: str) -> list:
    """Build standard PDF header with SevaSetu AI branding."""
    elements = []

    # Logo / brand row
    header_data = [[
        Paragraph(
            '<font color="#FF6B00"><b>SevaSetu AI</b></font>'
            ' <font color="#6b7280" size="9">🇮🇳 Made in India</font>',
            styles["body"]
        ),
        Paragraph(
            f'<font color="#6b7280" size="8">Generated: '
            f'{datetime.now().strftime("%d %b %Y, %I:%M %p")}</font>',
            ParagraphStyle("R", fontSize=8, textColor=GREY_TEXT, alignment=TA_RIGHT)
        ),
    ]]
    header_table = Table(header_data, colWidths=[100*mm, 80*mm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(header_table)
    elements.append(HRFlowable(width="100%", thickness=2, color=SAFFRON, spaceAfter=12))

    # Main title
    elements.append(Paragraph(title, styles["title"]))
    elements.append(Paragraph(subtitle, styles["subtitle"]))

    # User info strip
    user_strip_data = [[
        Paragraph(f"<b>Citizen:</b> {user_name}", styles["small"]),
        Paragraph(f"<b>By:</b> Rahul Jha | <b>SevaSetu AI v1.0</b>", styles["small"]),
    ]]
    user_strip = Table(user_strip_data, colWidths=[90*mm, 90*mm])
    user_strip.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    elements.append(user_strip)
    elements.append(Spacer(1, 10))
    return elements


def _build_footer(styles: dict) -> list:
    """Build standard disclaimer footer."""
    elements = [
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb"), spaceBefore=16),
        Paragraph(
            "⚠️ <b>Disclaimer:</b> This document is generated by SevaSetu AI for informational purposes only. "
            "For official guidance, please visit the respective government portals or contact nearest government office. "
            "Information is subject to change. | Developed by Rahul Jha | Made in India 🇮🇳",
            styles["footer"]
        ),
    ]
    return elements


# ── ENDPOINTS ────────────────────────────────────────────────────────────────

@router.get("/query/{query_id}", summary="Download query answer as PDF")
async def download_query_pdf(
    query_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
):
    """Generate and return a professional PDF for a specific AI query answer."""
    result = await db.execute(
        select(QueryHistory).where(
            QueryHistory.id == query_id,
            QueryHistory.user_id == current_user.id,
        )
    )
    query = result.scalar_one_or_none()
    if not query:
        raise HTTPException(status_code=404, detail="Query not found")

    pdf_bytes = _generate_query_pdf(query, current_user)

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="sevasetu_query_{query_id}.pdf"',
            "X-Generated-By": "SevaSetu AI - Made in India",
        },
    )


@router.get("/history", summary="Download full history as PDF")
async def download_history_pdf(
    limit: int = 20,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
):
    """Generate PDF of user's query history (last N queries)."""
    result = await db.execute(
        select(QueryHistory)
        .where(QueryHistory.user_id == current_user.id)
        .order_by(desc(QueryHistory.created_at))
        .limit(limit)
    )
    queries = result.scalars().all()

    if not queries:
        raise HTTPException(status_code=404, detail="No query history found")

    pdf_bytes = _generate_history_pdf(queries, current_user)

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": 'attachment; filename="sevasetu_history.pdf"',
        },
    )


@router.get("/checklist/{service_type}", summary="Download document checklist as PDF")
async def download_checklist_pdf(
    service_type: str,
    current_user: User = Depends(get_current_active_user),
):
    """Generate and download a styled document checklist PDF."""
    from ai.ocr.ocr_engine import ocr_engine
    checklist = ocr_engine.generate_checklist(service_type)
    pdf_bytes = _generate_checklist_pdf(checklist, current_user)

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="sevasetu_checklist_{service_type}.pdf"',
        },
    )


# ── PDF BUILDERS ──────────────────────────────────────────────────────────────

def _generate_query_pdf(query: QueryHistory, user: User) -> bytes:
    """Build a single query answer PDF."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=20*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )
    styles = _build_styles()
    elements = []

    # Header
    elements += _build_header(
        styles,
        title="Government Service Guidance",
        subtitle="AI-Generated Advisory by SevaSetu AI",
        user_name=user.name,
    )

    # Category badge
    cat = (query.category or "general").replace("_", " ").upper()
    cat_color = {
        "VOTER ID": SAFFRON, "PAN CARD": GREEN_IN, "PASSPORT": NAVY,
        "SCHEME": GOLD, "HEALTH SCHEME": GREEN_IN, "AGRICULTURE SCHEME": GREEN_IN,
    }.get(cat, NAVY)

    badge_data = [[Paragraph(f"📋 {cat}", styles["badge"])]]
    badge_table = Table(badge_data, colWidths=[40*mm])
    badge_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), cat_color),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("ROUNDEDCORNERS", [8, 8, 8, 8]),
    ]))
    elements.append(badge_table)
    elements.append(Spacer(1, 8))

    # Question
    elements.append(Paragraph("❓ Your Question", styles["heading"]))
    q_data = [[Paragraph(query.question, styles["body"])]]
    q_table = Table(q_data, colWidths=[170*mm])
    q_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#FFE4CC")),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    elements.append(q_table)
    elements.append(Spacer(1, 12))

    # AI Answer
    elements.append(Paragraph("🤖 SevaSetu AI Response", styles["heading"]))

    # Clean HTML tags from answer for PDF
    import re
    clean_answer = re.sub(r"<[^>]+>", "", query.ai_response)
    clean_answer = clean_answer.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")

    for para in clean_answer.split("\n"):
        para = para.strip()
        if para:
            elements.append(Paragraph(para, styles["body"]))

    elements.append(Spacer(1, 12))

    # Metadata table
    elements.append(Paragraph("📊 Query Information", styles["heading"]))
    meta_data = [
        ["Field", "Value"],
        ["Query ID", f"#{query.id}"],
        ["Category", query.category or "General"],
        ["Language", {"en": "English", "hi": "Hindi", "mr": "Marathi"}.get(query.language, "English")],
        ["AI Confidence", f"{int((query.confidence or 0) * 100)}%"],
        ["Asked On", datetime.fromisoformat(str(query.created_at)).strftime("%d %b %Y, %I:%M %p") if query.created_at else "N/A"],
    ]
    meta_table = Table(meta_data, colWidths=[50*mm, 120*mm])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(meta_table)

    # Footer
    elements += _build_footer(styles)

    doc.build(elements)
    return buffer.getvalue()


def _generate_checklist_pdf(checklist: dict, user: User) -> bytes:
    """Build a document checklist PDF with status indicators."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=20*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )
    styles = _build_styles()
    elements = []

    elements += _build_header(
        styles,
        title=checklist.get("title", "Document Checklist"),
        subtitle="Required documents for your government service application",
        user_name=user.name,
    )

    # Info strip
    if checklist.get("online_portal"):
        elements.append(Paragraph(
            f"🌐 <b>Portal:</b> {checklist['online_portal']}   "
            f"📞 <b>Helpline:</b> {checklist.get('helpline', 'N/A')}   "
            f"📋 <b>Form:</b> {checklist.get('form', 'N/A')}   "
            f"💰 <b>Fee:</b> {checklist.get('fee', 'Free')}",
            styles["body"]
        ))
        elements.append(Spacer(1, 10))

    # Documents table
    elements.append(Paragraph("📋 Required Documents", styles["heading"]))

    table_data = [["#", "Document", "Status", "Purpose"]]
    status_colors = {
        "required": SAFFRON, "optional": NAVY,
        "completed": GREEN_IN, "conditional": GOLD,
    }

    for i, doc_item in enumerate(checklist.get("documents", []), 1):
        status = doc_item.get("status", "required")
        table_data.append([
            str(i),
            doc_item.get("name", ""),
            status.upper(),
            doc_item.get("purpose", ""),
        ])

    doc_table = Table(table_data, colWidths=[10*mm, 60*mm, 25*mm, 75*mm])
    doc_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (2, 0), (2, -1), "CENTER"),
    ]))
    elements.append(doc_table)
    elements.append(Spacer(1, 12))

    # Tips
    elements.append(Paragraph("💡 Important Tips", styles["heading"]))
    tips = [
        "Carry both original and self-attested photocopies of all documents.",
        "Ensure all documents are in good condition and clearly readable.",
        "Check online portal for latest fee structure before applying.",
        "Keep a copy of acknowledgment / reference number after submission.",
        "For any issues, call the helpline number provided above.",
    ]
    for tip in tips:
        elements.append(Paragraph(f"• {tip}", styles["body"]))

    elements += _build_footer(styles)
    doc.build(elements)
    return buffer.getvalue()


def _generate_history_pdf(queries: list, user: User) -> bytes:
    """Build a history export PDF with all recent queries."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=20*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )
    styles = _build_styles()
    elements = []

    elements += _build_header(
        styles,
        title="Query History Report",
        subtitle=f"Last {len(queries)} interactions with SevaSetu AI",
        user_name=user.name,
    )

    for i, q in enumerate(queries, 1):
        import re
        clean = re.sub(r"<[^>]+>", "", q.ai_response)[:300] + "..."

        block = [
            [Paragraph(f"<b>Q{i}. {q.question}</b>", styles["body"])],
            [Paragraph(clean, styles["small"])],
            [Paragraph(
                f"Category: {q.category or 'General'} | "
                f"Language: {q.language or 'en'} | "
                f"Confidence: {int((q.confidence or 0)*100)}% | "
                f"Date: {str(q.created_at)[:16]}",
                styles["small"]
            )],
        ]
        block_table = Table(block, colWidths=[170*mm])
        block_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG if i % 2 == 0 else WHITE),
            ("PADDING", (0, 0), (-1, -1), 8),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
            ("TOPPADDING", (0, 0), (-1, 0), 10),
        ]))
        elements.append(block_table)
        elements.append(Spacer(1, 6))

    elements += _build_footer(styles)
    doc.build(elements)
    return buffer.getvalue()
